/* e_hss_err.c */
/* ====================================================================
 * Copyright (c) 1999-2018 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.OpenSSL.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@OpenSSL.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.OpenSSL.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

/*
 * NOTE: this file was auto generated by the mkerr.pl script: any changes
 * made to it will be overwritten when the script next updates this file,
 * only reason strings will be preserved.
 */

#include <stdio.h>
#include <openssl/err.h>
#include "hss_err.h"

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(0,func,0)
# define ERR_REASON(reason) ERR_PACK(0,0,reason)

static ERR_STRING_DATA HSS_str_functs[] = {
    {ERR_FUNC(HSS_F_HSS_DO_SIGN), "HSS_DO_SIGN"},
    {ERR_FUNC(HSS_F_HSS_DO_VERIFY), "HSS_DO_VERIFY"},
    {ERR_FUNC(HSS_F_HSS_ENGINE_CODE), "HSS_ENGINE_CODE"},
    {ERR_FUNC(HSS_F_HSS_KEYGEN), "HSS_KEYGEN"},
    {ERR_FUNC(HSS_F_HSS_LOAD_WORKING_KEY), "HSS_LOAD_WORKING_KEY"},
    {ERR_FUNC(HSS_F_HSS_NEW_SIG), "HSS_NEW_SIG"},
    {ERR_FUNC(HSS_F_HSS_PKEY_INIT), "HSS_PKEY_INIT"},
    {ERR_FUNC(HSS_F_HSS_PKEY_KEYGEN), "HSS_PKEY_KEYGEN"},
    {ERR_FUNC(HSS_F_HSS_PKEY_PARAM_DECODE), "HSS_PKEY_PARAM_DECODE"},
    {ERR_FUNC(HSS_F_HSS_PKEY_PRIV_DECODE), "HSS_PKEY_PRIV_DECODE"},
    {ERR_FUNC(HSS_F_HSS_PKEY_PRIV_ENCODE), "HSS_PKEY_PRIV_ENCODE"},
    {ERR_FUNC(HSS_F_HSS_PKEY_PUB_DECODE), "HSS_PKEY_PUB_DECODE"},
    {ERR_FUNC(HSS_F_HSS_PKEY_PUB_ENCODE), "HSS_PKEY_PUB_ENCODE"},
    {ERR_FUNC(HSS_F_HSS_PKEY_SIGN), "HSS_PKEY_SIGN"},
    {ERR_FUNC(HSS_F_HSS_SIG_SIZE), "HSS_SIG_SIZE"},
    {ERR_FUNC(HSS_F_HSS_VERIFY), "HSS_VERIFY"},
    {0, NULL}
};

static ERR_STRING_DATA HSS_str_reasons[] = {
    {ERR_REASON(HSS_R_ASN1_DECODE_ERROR), "asn1 decode error"},
    {ERR_REASON(HSS_R_ASN1_ENCODE_ERROR), "asn1 encode error"},
    {ERR_REASON(HSS_R_ASN1_PARAMETER_DECODE_ERROR),
     "asn1 parameter decode error"},
    {ERR_REASON(HSS_R_DECODE_ERROR), "decode error"},
    {ERR_REASON(HSS_R_EXPECTED_NULL_POINTER), "expected null pointer"},
    {ERR_REASON(HSS_R_INVALID_PARAM_VALUE), "invalid param value"},
    {ERR_REASON(HSS_R_MALLOC_FAILURE), "malloc failure"},
    {ERR_REASON(HSS_R_NULL_POINTER_ERROR), "null pointer error"},
    {ERR_REASON(HSS_R_NULL_SIGNATURE_LENGTH_POINTER),
     "null signature length pointer"},
    {ERR_REASON(HSS_R_PKCS8_DECODE_ERROR), "pkcs8 decode error"},
    {ERR_REASON(HSS_R_PKCS8_ENCODE_ERROR), "pkcs8 encode error"},
    {ERR_REASON(HSS_R_PKEY_ASSIGNMENT_ERROR), "pkey assignment error"},
    {ERR_REASON(HSS_R_SYSTEM_FAILURE), "system failure"},
    {ERR_REASON(HSS_R_X509_DECODE_ERROR), "x509 decode error"},
    {ERR_REASON(HSS_R_X509_ENCODE_ERROR), "x509 encode error"},
    {0, NULL}
};

#endif

#ifdef HSS_LIB_NAME
static ERR_STRING_DATA HSS_lib_name[] = {
    {0, HSS_LIB_NAME},
    {0, NULL}
};
#endif

static int HSS_lib_error_code = 0;
static int HSS_error_init = 1;

void ERR_load_HSS_strings(void)
{
    if (HSS_lib_error_code == 0)
        HSS_lib_error_code = ERR_get_next_error_library();

    if (HSS_error_init) {
        HSS_error_init = 0;
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(HSS_lib_error_code, HSS_str_functs);
        ERR_load_strings(HSS_lib_error_code, HSS_str_reasons);
#endif

#ifdef HSS_LIB_NAME
        HSS_lib_name->error = ERR_PACK(HSS_lib_error_code, 0, 0);
        ERR_load_strings(0, HSS_lib_name);
#endif
    }
}

void ERR_unload_HSS_strings(void)
{
    if (HSS_error_init == 0) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(HSS_lib_error_code, HSS_str_functs);
        ERR_unload_strings(HSS_lib_error_code, HSS_str_reasons);
#endif

#ifdef HSS_LIB_NAME
        ERR_unload_strings(0, HSS_lib_name);
#endif
        HSS_error_init = 1;
    }
}

void ERR_HSS_error(int function, int reason, char *file, int line)
{
    if (HSS_lib_error_code == 0)
        HSS_lib_error_code = ERR_get_next_error_library();
    ERR_PUT_error(HSS_lib_error_code, function, reason, file, line);
}
