/* ====================================================================
 * Copyright (c) 2001-2017 The OpenSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer. 
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@openssl.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE OpenSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE OpenSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 *
 * This product includes cryptographic software written by Eric Young
 * (eay@cryptsoft.com).  This product includes software written by Tim
 * Hudson (tjh@cryptsoft.com).
 *
 */

#ifndef HEADER_HSS_ERR_H
# define HEADER_HSS_ERR_H

# ifdef  __cplusplus
extern "C" {
# endif

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */

void ERR_load_HSS_strings(void);
void ERR_unload_HSS_strings(void);
void ERR_HSS_error(int function, int reason, char *file, int line);
# define HSSerr(f,r) ERR_HSS_error((f),(r),__FILE__,__LINE__)

/* Error codes for the HSS functions. */

/* Function codes. */
# define HSS_F_HSS_DO_SIGN                                101
# define HSS_F_HSS_DO_VERIFY                              102
# define HSS_F_HSS_ENGINE_CODE                            100
# define HSS_F_HSS_KEYGEN                                 103
# define HSS_F_HSS_LOAD_WORKING_KEY                       115
# define HSS_F_HSS_NEW_SIG                                104
# define HSS_F_HSS_PKEY_INIT                              105
# define HSS_F_HSS_PKEY_KEYGEN                            106
# define HSS_F_HSS_PKEY_PARAM_DECODE                      107
# define HSS_F_HSS_PKEY_PRIV_DECODE                       108
# define HSS_F_HSS_PKEY_PRIV_ENCODE                       109
# define HSS_F_HSS_PKEY_PUB_DECODE                        110
# define HSS_F_HSS_PKEY_PUB_ENCODE                        111
# define HSS_F_HSS_PKEY_SIGN                              112
# define HSS_F_HSS_SIG_SIZE                               113
# define HSS_F_HSS_VERIFY                                 114

/* Reason codes. */
# define HSS_R_ASN1_DECODE_ERROR                          100
# define HSS_R_ASN1_ENCODE_ERROR                          101
# define HSS_R_ASN1_PARAMETER_DECODE_ERROR                102
# define HSS_R_DECODE_ERROR                               103
# define HSS_R_EXPECTED_NULL_POINTER                      104
# define HSS_R_INVALID_PARAM_VALUE                        105
# define HSS_R_MALLOC_FAILURE                             106
# define HSS_R_NULL_POINTER_ERROR                         107
# define HSS_R_NULL_SIGNATURE_LENGTH_POINTER              108
# define HSS_R_PKCS8_DECODE_ERROR                         109
# define HSS_R_PKCS8_ENCODE_ERROR                         110
# define HSS_R_PKEY_ASSIGNMENT_ERROR                      111
# define HSS_R_SYSTEM_FAILURE                             112
# define HSS_R_X509_DECODE_ERROR                          113
# define HSS_R_X509_ENCODE_ERROR                          114

# ifdef  __cplusplus
}
# endif
#endif
